### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by jasonhildebrand** [egenix/egenix-mx-base-python-2x3#12]
@malemburg, I have a couple of legacy apps that require mx.DateTime.  I am trying to assess whether to port these  apps to use Python's native datetime instead.

Was the effort to update mx.DateTime for Python 3 successful?  Is there an intent to maintain mx.DateTime on an ongoing basis? (I haven't seen any commits since 2015...)

Thanks for any information you can provide.

**Comment by malemburg** [comment]
Hi Jason,

there has been no progress since the sprint in 2015. I have been too
busy with other projects. There may be some more progress this year,
but I wouldn't hold your breath.

Porting t Python 3's datetime is probably the safer bet.

Thanks,
-- 
Marc-Andre Lemburg
http://www.malemburg.com/

**Comment by jasonhildebrand** [comment]
OK, that's what I was thinking.  I appreciate the update.
